name: Generate Folder Index

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Generate index.html and README.md
        run: |
          # Create a script to generate the HTML and README files
          cat > generate-index.js << 'EOF'
          const fs = require('fs');
          const path = require('path');
          
          // Get all directories in the root folder
          const getDirectories = () => {
            return fs.readdirSync('.', { withFileTypes: true })
              .filter(dirent => dirent.isDirectory())
              .filter(dirent => !dirent.name.startsWith('.')) // Exclude hidden directories
              .map(dirent => dirent.name)
              .sort();
          };
          
          // Generate HTML
          const generateHTML = (directories) => {
            const html = `<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Tsvetelina Kaneva's 5 min exercises</title>
              <style>
                  body {
                      font-family: 'Arial', sans-serif;
                      line-height: 1.6;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                      background-color: #f8f9fa;
                      color: #333;
                  }
                  h1 {
                      text-align: center;
                      margin-bottom: 40px;
                      color: #2c3e50;
                      border-bottom: 2px solid #3498db;
                      padding-bottom: 10px;
                  }
                  .folder-container {
                      display: flex;
                      flex-direction: column;
                      align-items: center;
                      gap: 20px;
                  }
                  .folder-link {
                      display: inline-block;
                      font-size: 1.2rem;
                      text-decoration: none;
                      color: #3498db;
                      padding: 10px 20px;
                      border-radius: 5px;
                      background-color: #ffffff;
                      box-shadow: 0 2px 5px rgba(0,0,0,0.1);
                      transition: all 0.3s ease;
                      width: 80%;
                      text-align: center;
                  }
                  .folder-link:hover {
                      background-color: #3498db;
                      color: white;
                      transform: translateY(-2px);
                      box-shadow: 0 4px 8px rgba(0,0,0,0.2);
                  }
                  footer {
                      margin-top: 50px;
                      text-align: center;
                      font-size: 0.9rem;
                      color: #7f8c8d;
                  }
              </style>
          </head>
          <body>
              <h1>Tsvetelina Kaneva's 5 min exercises</h1>
              <div class="folder-container">
                  ${directories.map(dir => `<a href="${dir}/" class="folder-link">${dir}</a>`).join('\n                  ')}
              </div>
              <footer>
                  Auto-generated on ${new Date().getDate()}.${new Date().getMonth() + 1}.${new Date().getFullYear()}
              </footer>
          </body>
          </html>`;
            
            fs.writeFileSync('index.html', html);
            console.log('index.html has been generated');
          };
          
          // Generate README.md with support for different case variations
          const generateReadme = (directories) => {
            const date = new Date();
            const formattedDate = date.getDate() + '.' + (date.getMonth() + 1) + '.' + date.getFullYear();
            
            // Check for different README filename variations
            const readmeVariations = ['README.md', 'readme.md', 'Readme.md'];
            let existingReadmePath = null;
            let existingContent = '';
            
            // Find if any README variation exists
            for (const readmeName of readmeVariations) {
              if (fs.existsSync(readmeName)) {
                existingReadmePath = readmeName;
                existingContent = fs.readFileSync(readmeName, 'utf8');
                console.log('Found existing README at: ' + readmeName);
                break;
              }
            }
            
            // Default output path - prefer existing one or fallback to README.md
            const outputPath = existingReadmePath || 'README.md';
            console.log('Will write to: ' + outputPath);
            
            // Prepare links content with domain prepended to URLs
            const folderLinks = directories.map(dir => '- [' + dir + '](https://5-mins.tskaneva.com/' + dir + '/)').join('\n');
            
            // If no README exists, create a new one
            if (!existingReadmePath) {
              console.log('No existing README found, creating new one');
              const markdown = '# Tsvetelina Kaneva\'s 5 min exercises\n\n' +
                               '<!-- [links] -->\n' +
                               folderLinks + '\n' +
                               '<!-- [/links] -->\n\n' +
                               '---\n\n' +
                               'Auto-generated on ' + formattedDate;
              
              fs.writeFileSync(outputPath, markdown);
              console.log('New ' + outputPath + ' has been generated');
              return;
            }
            
            // Check if the [links] tag exists
            const linksTagRegex = /<!-- \[links\] -->([\s\S]*?)<!-- \[\/links\] -->/;
            
            if (linksTagRegex.test(existingContent)) {
              console.log('Found [links] tag in README, updating content between tags');
              // Replace content between tags
              const updatedContent = existingContent.replace(
                linksTagRegex, 
                '<!-- [links] -->\n' + folderLinks + '\n<!-- [/links] -->'
              );
              fs.writeFileSync(outputPath, updatedContent);
            } else {
              console.log('No [links] tag found in README, appending to the end');
              // Add tags and links if they don't exist
              const updatedContent = existingContent + 
                                    '\n\n<!-- [links] -->\n' + 
                                    folderLinks + 
                                    '\n<!-- [/links] -->\n\n---\n\n' +
                                    'Auto-generated on ' + formattedDate;
              fs.writeFileSync(outputPath, updatedContent);
            }
            
            console.log(outputPath + ' has been updated with folder links');
          };
          
          const directories = getDirectories();
          generateHTML(directories);
          generateReadme(directories);
          EOF
          
          # Execute the script
          node generate-index.js
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          # Only add files that exist
          if [ -f "index.html" ]; then git add index.html; fi
          if [ -f "README.md" ]; then git add README.md; fi
          if [ -f "readme.md" ]; then git add readme.md; fi
          if [ -f "Readme.md" ]; then git add Readme.md; fi
          # Check if there are changes to commit
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update index.html and README files with folder listing")
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}